version = 1
SPDX-PackageName = "gif-tools"
SPDX-PackageSupplier = "Igor Mironchik <igor.mironchik@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/igormironchik/gif-tools"

[[annotations]]
path = ["editor.png", "recorder.png", "src/recorder/*.ui", "src/shared/icon.ico", "src/editor/gif-editor.rc", "src/recorder/gif-recorder.rc", "src/editor/resources.qrc", "src/recorder/resources.qrc", "README.md", ".gitignore", ".github/**", ".gitmodules", "REUSE.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Igor Mironchik <igor.mironchik@gmail.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "src/shared/icon/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["src/editor/img/**", "src/recorder/img/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2007 Nuno Pinheiro <nuno@oxygen-icons.org>, 2007 David Vignoni <david@icon-king.com>, 2007 David Miller <miller@oxygen-icons.org>, Johann Ollivier Lapeyre <johann@oxygen-icons.org>, Kenneth Wimer <kwwii@bootsplash.org>, 2007 Riccardo Iaconelli <riccardo@oxygen-icons.org>"
SPDX-License-Identifier = "LGPL-3.0-or-later"

[[annotations]]
path = "src/shared/img/Qt-logo-neon-transparent.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 The Qt Company Ltd and other contributors"
SPDX-License-Identifier = "LGPL-3.0-or-later"
