
name: "deploy_win"

on:
  workflow_dispatch:

jobs:
  windows:
    name: windows
    runs-on: windows-2022
 
    strategy:
      fail-fast: true
      matrix:
        language: ['cpp']
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
         
    - name: Set PATH to Qt
      run: |
        $qt_version = Get-Content ${{ github.workspace }}\script\qt.version -TotalCount 1
        $qt_arch = Get-Content ${{ github.workspace }}\script\qt.arch.win -TotalCount 1
        echo "${{ github.workspace }}\Qt\$qt_version\$qt_arch\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
     
    - name: Install Qt
      run: cmd /c "script\windows\install-qt.bat"

    - name: Enable NMake
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      run: cmd /c "script\windows\build.bat"
       
    - name: Copy binaries
      run: cmd /c "script\windows\copy-binaries.bat"
       
    - name: Deploy
      run: cmd /c "script\windows\deploy.bat"
      
    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: GIF_Windows_x64.Installer.exe
        path: GIF_Windows_x64.Installer.exe
